LPDDR5 7 Series PHY
antmicro/litedram pull request #2
Opened 2021-08-12 09:12 UTC by piotr-binkowski

This is continuation of #1 with only change that commits were rebased on top of LPDDR5 branch which is currently being merged to upstream

2021-08-12 10:03 UTC, jedrzejboczar requested changes
This looks good. I added some comments in the code. The main thing that we could change is to use sys+sys4x clocks instead of sys2x+sys8x as the LPDDR5 has DFI set up differently and we don't need that big clock ratio. By adding compatibility with DFI Rate Converter we will be able to increase the ratio if needed.

2021-08-12 10:03 UTC, jedrzejboczar commented on litedram/phy/lpddr5/basephy.py
> +        read_des_delay  = des_latency.sys8x//8 + bitslip_cycles+bitslip_range + burst_ck_cycles  # DQ -> DFI rddata
When we modify S7LPDDR5PHY to use sys+sys4x instead of sys2x+sys8x this change shouldn't be necessary.

2021-08-12 10:03 UTC, jedrzejboczar commented on litedram/phy/lpddr5/s7phy.py
> +        self.settings.read_level = True
Typo, should be "read_leveling": https://github.com/antmicro/litedram/blob/jboc/lpddr5-rebase/litedram/common.py#L229

2021-08-12 10:03 UTC, jedrzejboczar commented on litedram/phy/lpddr5/s7phy.py
> +            return o
We can add csr_cdc argument and use it the same as in LPDDR5PHY (and then pass it via `super().__init__`):
https://github.com/antmicro/litedram/blob/jboc/lpddr5-rebase/litedram/phy/lpddr5/basephy.py#L211-L217
This will enable compatibility with the automatic wrapper from DFI rate converter:
https://github.com/antmicro/litedram/blob/jboc/lpddr5-rebase/litedram/phy/dfi.py#L243-L245
It can then be tested by adding the DRAM PHY to the SoC in the following way:
https://github.com/antmicro/litedram/blob/jboc/lpddr5-rebase/litedram/phy/lpddr5/simsoc.py#L108-L143

2021-08-12 10:03 UTC, jedrzejboczar commented on litedram/phy/lpddr5/s7phy.py
> +            des_latency = Latency(sys2x=2),  # ISERDESE2 NETWORKING
After moving to sys+sys4x this latency will be in sys clock cycles.

2021-08-19 12:09 UTC, piotr-binkowski commented on litedram/phy/lpddr5/basephy.py
> +        read_des_delay  = des_latency.sys8x//8 + bitslip_cycles+bitslip_range + burst_ck_cycles  # DQ -> DFI rddata
Right, when using sys+sys4x this change is no longer needed and was removed

2021-08-19 12:12 UTC, piotr-binkowski commented on litedram/phy/lpddr5/s7phy.py
> +        self.settings.read_level = True
Fixed

2021-08-19 12:13 UTC, piotr-binkowski commented on litedram/phy/lpddr5/s7phy.py
> +            des_latency = Latency(sys2x=2),  # ISERDESE2 NETWORKING
This now uses `sys` clock cycles

2021-08-19 13:36 UTC, piotr-binkowski commented on litedram/phy/lpddr5/s7phy.py
> +            return o
I've added that argument, tested it with a modified platform that has DFIRateConverter and the generated verilog shows that clocks are modified correctly with it.

2021-08-19 13:46 UTC, piotr-binkowski commented
@jedrzejboczar PTAL

2021-08-19 14:07 UTC, piotr-binkowski commented
For a quick test you can use the modified platform & target here https://github.com/antmicro/litex-boards/tree/pbin/lpddr5 which instantiates the LPDDR5 PHY

2021-08-26 15:55 UTC, jedrzejboczar approved these changes
LGTM. We will need to test it on hardware when it's available (maybe it'll need some minor tweaks), but I think it's good to merge now. I see this also adds write leveling support in software (via init.py), but we'll yet need to add support for write leveling mode in the PHY (but it can be done in separate PR).

2021-08-30 15:11 UTC, merged